### ISSUE TITLE
What is this?

### ISSUE THREAD

**Issue by cincarnato** [ScorpioT1000/doctrine-orm-transformations#9]
What is this?

(\Indaxia\OTR\Traits\Transformable) line 42 

```
  if($pn[0] === '_' && $pn[1] === '_') { continue; }
```

**Comment by ScorpioT1000** [comment]
It's the underline tags to ignore any fields starting from "__", including "__meta". Helps to sort out incoming javascript trash

https://github.com/Indaxia/doctrine-orm-transformations/blob/master/src/Traits/Transformable.php#L42

**Comment by cincarnato** [comment]
Thanks!
